# Generated by Django 3.2.1 on 2021-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=55)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('taille', models.IntegerField()),
            ],
        ),
    ]
