# Generated by Django 3.2.1 on 2021-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerrariumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='humidite',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
