# Generated by Django 3.2.1 on 2021-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerrariumApp', '0003_auto_20210504_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='humidite',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
