# Generated by Django 3.2.1 on 2021-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerrariumApp', '0008_auto_20210504_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='humidite',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
    ]
