# Generated by Django 3.2.1 on 2021-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerrariumApp', '0009_alter_terrarium_humidite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='humidite',
            field=models.DecimalField(decimal_places=1, max_digits=100000000),
        ),
    ]
