# Generated by Django 3.2.1 on 2021-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerrariumApp', '0011_alter_terrarium_humidite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='humidite',
            field=models.IntegerField(),
        ),
    ]
